version: '3'
services:
    rasa:
      user: root
      build: 
        context: ./rasa/openHPI_de
      volumes:
      - "./rasa/openHPI_de:/app"
      ports: 
        - "10010:5005"
    action_server:
      build: 
        context: ./rasa/openHPI_de/actions
      volumes:
        - ./rasa/openHPI_de/actions:/app/actions
        - ./rasa/openHPI_de/data:/app/data
        - ./rasa/openHPI_de/action_responses:/app/action_responses
      ports:
        - 10011:5055
